name: Hello World
on: [pull_request]
jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Run a single-line script
        run: |
          ls
          apt install shadowsocks -y
          sssever --help