name: Hello World
on: [push, pull_reqeust]
jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Run a single-line script
        run: echo "Hello World!"
  my_second_job:
    name: My Second Job
    runs-on: macos-latest
    steps:
      - name: Run a multi-line script
        env:
          MY_VAR: Hello World!
          MY_NAME: shellhub
        run: |
          echo $MY_VAR
          echo My name is $MY_NAME